### ISSUE TITLE
Add UI for loading molecules

### ISSUE THREAD

**Issue by formulanano** [formulanano/nanocar-builder-web#1]
There should be some sort of UI which will allow the user to load a molecule from a list. Also, it should allow user to delete the molecule as well. This could be a good start but we would definitely need more functionality in the future to edit (move, delete, change) individual atoms.

I can provide the necessary molecule files but I am not sure how to go about loading a file. Any help is appreciated.

### Turkish
Istenilen herhangi bir molekulun ekrana getirilebilmesi ve daha sonra da silinebilmesi icin bir arayuz gerekiyor. Bu bence iyi bir baslangic olur daha sonra atom seviyesinde desigiklik yapmayi saglaycak ozellikler getirilmesi gerekecek.

Molekul dosyalarini ben saglayabilirim, bu konuda calismak isteyenler buraya yazabilir.

**Comment by 98oktay** [comment]
Selam, 

Bu konuda React.js ve Semantic-UI kullanarak bi arayüz çalışması yaptım aslında, projeye dahil edilirsem pull-request gönderebilirim.

**Comment by formulanano** [comment]
Cok guzel, tesekkurler calisman icin. Ben seni bu issue ya atadim. Repo acik halde fork edip, istedigin gibi pull-request acabilirsin.

**Comment by drac** [comment]
Issue #17 on [implement UI/UX design](https://github.com/formulanano/nanocar-builder-web/milestone/1) milestone provides solution for this issue.
