### ISSUE TITLE
What is the best way to deploy this app to the formulanano website?

### ISSUE THREAD

**Issue by formulanano** [formulanano/nanocar-builder-web#2]
This web app will be hosted through github in the [formulanano.com website](https://github.com/formulanano/formulanano.github.io). However I think this repository should be separate. I am not sure what is the best way to update the website as this app is being developed.

### Turkish
Bu web uygulamasi [formulanano websitesinin](https://github.com/formulanano/formulanano.github.io) bir parcasi olmasina ragmen ayri bir repo da gelistirilmesi daha uygun diye dusunuyorum. Fakat, bu uygulama gelistikce bunun websitesine yansimasinin otomatik ve kolay bir yontemi var mi emin degilim. Yoksa her seferinde elle kopyalamak mi gerekli?

**Comment by bilalbaraz** [comment]
There is an option to deploy easily: [DeployBot](https://deploybot.com/) It detects automatically and update the server-side, when you commit/merge to master. It has many feature that you can use, it can trigger any command on server before/after deployment. I hope I got you right.

**Comment by hamzaerbay** [comment]
Another option is [Netlify](https://www.netlify.com/). It's doing something similar w/ Deploybot.  It's pretty handy I'm using that for my personal website. They also provide free SSL and free hosting for one project.

**Comment by arslanberk** [comment]
Depending on the planned future of this application, using github pages may not be enough to host the application. I would like you to check Amazon Web Services and their free tier.
In any case, deploying an application to a server can be automated with CI/CD tools for example  [Travis](https://about.travis-ci.com/) which is a cloud-based application, or [Jenkins](https://jenkins.io/) which needs to be installed and configured on server. These tools can run tests and if all tests succeed then it can update server. These tools can also update github readme with the status of the latest test.
I can also recommend to use [SonarCloud](https://sonarcloud.io/about) which can measure the code quality and coverage. It is free to use for open source projects.

**Comment by drac** [comment]
checkout [Implement Continuous Deployment](https://github.com/formulanano/nanocar-builder-web/milestone/2) milestone for further information
