### ISSUE TITLE
Security alerts for some node packages

### ISSUE THREAD

**Issue by formulanano** [formulanano/nanocar-builder-web#4]
It seems like the last pull requesr (#3 ) resulted in some security alerts. Namely, `open`, `shelljs`, `eslint`, `braces`, `js-yaml`, `webpack-dev-serve`, `mime` packages need to be updated. I tried fixing this with npm by `npm audit fix --force` but this results the build to fail. @98oktay would you be able to update these dependencies in a non-breaking manner?

**Comment by hamzaerbay** [comment]
I'm on it.
