### ISSUE TITLE
[Discussion] Creating a roadmap, milestones , strategy

### ISSUE THREAD

**Issue by drac** [formulanano/nanocar-builder-web#5]
Roadmap, tasks, issues and milestones for **v1.0.0** need to be defined so anyone who wants to contribute will know what is needed to be done/implemented.

**So the question here is;**
Can we provide some milestones/roadmap transparently, so everyone knows what to focus on next ? (more about milestones can be found [here](https://help.github.com/en/articles/about-milestones))

**Comment by cagatayikim** [comment]
It's right. Beginners like me don't know what to do. Milestones will provide great productivity for both the project and the people.

**Comment by kbsezginel** [comment]
That's a very good suggestion, I was thinking about how to delegate work and make it easier for people to work on smaller parts of the project. I will read more about milestones and try to come up with a roadmap soon. In the meantime please feel free to create more issues, these are very helpful.

**Comment by drac** [comment]
Roadmap, milestones and strategy started to emerge. I'm closing the issue because there is no further discussion. We can re-open the issue for further discussions.
