### ISSUE TITLE
[Discussion] Why we didn't use create-react-app for bootstrapping and kickstarting the project?

### ISSUE THREAD

**Issue by drac** [formulanano/nanocar-builder-web#6]
It would be better to use create-react-app to kickstart the project without any struggle.

**[create-react-app](https://facebook.github.io/create-react-app/docs/getting-started)** provides all the necessary reactjs environment (testing framework included).

**Comment by rizasam** [comment]
@drac We need .scss loader for styling. But create-react-app not support to import. Therefore eject CRA and edited web-pack config files.

If you can help with .scss loader, I would like to re-create create-react-app.

**Comment by 98oktay** [comment]
@drac We need .scss loader for styling. But create-react-app not support to import. Therefore eject CRA and edited web-pack config files.

If you can help with .scss loader, I would like to re-create create-react-app.

**Comment by drac** [comment]
@98oktay in the [create-react-app docs](https://facebook.github.io/create-react-app/docs/adding-a-sass-stylesheet) I found that there is a way for adding Sass stylesheets.

**Comment by formulanano** [comment]
I am not knowledgeable about react enough to say which is better but from what I can understand this would result in a more lightweight codebase right? What are some benefits of using this and would you be able to implement it?

**Comment by drac** [comment]
> What are some benefits of using this...

`create-react-app` initialises a react project for you that organised, structured, tuned for performance and developer experience. Best thing about it that it saves a lot of time to kickstart a project.

> would you be able to implement it?

Sure, I can implement it

**Comment by hamzaerbay** [comment]
> It would be better to use create-react-app to kickstart the project without any struggle.
> 
> **[create-react-app](https://facebook.github.io/create-react-app/docs/getting-started)** provides all the necessary reactjs environment (testing framework included).

I worked w/ extracted CRA and extracted CRA. Sometimes that was pretty weird to integrate something. Therefore, I created a [starter kit](https://github.com/hamzaerbay/react-starter-kit) for my experimental projects. We could fork it or make a similar setup. FYI

**Comment by 98oktay** [comment]
@hamzaerbay I examined your starter-kit. Webpack config are extracted. Pretty nice and convenient. Using this can solve problems. I'm in favor of using this.
